### ISSUE TITLE
NUS-WIDE 数据集

### ISSUE THREAD

**Issue by xueliang** [TreezzZ/DPSH_PyTorch#1]
你好，
    请问NUS-WIDE数据集的四个文件，能公开一下吗？目前官网上面的URL，很多Flickr图像已经被删除了。

**Comment by TreezzZ** [comment]
> 你好，
> 请问NUS-WIDE数据集的四个文件，能公开一下吗？目前官网上面的URL，很多Flickr图像已经被删除了。

你好，NUS-WIDE数据集下载地址我已经更新到README里了。我使用的数据集是在NUS-WIDE中取最多的21类构成的NUS-WIDE-TC21数据集，共有四个文件"nus-wide-tc21-iall.mat", "nus-wide-tc21-lall.mat", "nus-wide-tc21-xall.mat", "nus-wide-tc21-yall.mat"。其中前两个文件分别是图像和标签的matlab文件格式，后面两个我没有用到。我把前面两个.mat格式转换成了numpy的npy格式上传到了网盘中。因为这个数据集我也是前几天刚从师兄那里拷过来的，如果你想要原始图像文件的话我这里没有保存
