### ISSUE TITLE
OOM：out of memory

### ISSUE THREAD

**Issue by ray0809** [TreezzZ/DPSH_PyTorch#2]
您好，当我取cifar10整体训练的5w张拿来训练，存在一个显存溢出问题，请问你这边训练是用了多少数据

**Comment by TreezzZ** [comment]
> 您好，当我取cifar10整体训练的5w张拿来训练，存在一个显存溢出问题，请问你这边训练是用了多少数据

按照论文原文，取1000张作为查询图像，5000张作为训练图像。训练完成后，对所有图像生成hash code，然后用1000个查询图像计算mAP。
我记得我最开始的时候也是直接用cifar10所有的数据来训练的，没有溢出的问题。你检查一下是不是batch-size设置的太大了？

**Comment by ray0809** [comment]
发现是我自己改动了代码的原因，感谢你的回答～
